"""add_trip_relationships

Revision ID: 01e0bdeace01
Revises: b454fb5e48ea
Create Date: 2026-07-18 09:06:34.621480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01e0bdeace01'
down_revision: Union[str, Sequence[str], None] = 'b454fb5e48ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_stuff')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_stuff', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
