"""is_stuff user added

Revision ID: a1214eef5bab
Revises: 1f78c83bfa2b
Create Date: 2026-07-16 13:06:51.730497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1214eef5bab'
down_revision: Union[str, Sequence[str], None] = '1f78c83bfa2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_stuff', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_stuff')
    # ### end Alembic commands ###
